### ISSUE TITLE
8 new rare tiles

### ISSUE THREAD

**Issue by Veracity0** [Loathing-Associates-Scripting-Society/combo#5]
Hi. I have new tiles to submit for this project.

I've been running Veracity's BeachComber for a few years and I have encountered the following:

1 whale
1 message in a bottle
1 cursed cutlass
42 pieces of driftwood

I have prepared a spreadsheet of all my "scarce" (or is it "rare"?) squares.

I'm happy to provide it to you.

Or, I'd be happy to submit a pull request with the 8 new tiles. It's ready to go. I tried. It was rejected.

Unfortunately, I do not have permission to make a pull request. A pity, since you are not obligated to accept it, anyway. Give me permission to submit a PR and I will try again.

I'll attach the .xlsx file and you can do the work to find the new data. Fortunately, one of the columns is generated JSON lines that can be simply added to your data file.

[BeachScarce.xlsx](https://github.com/Loathing-Associates-Scripting-Society/combo/files/7879401/BeachScarce.xlsx)

**Comment by spaghetti-squash** [comment]
Thank you so much for these valuable data! I'm looking through all our permissions settings and am unable to see at present why you aren't able to submit a PR. I'll keep digging.

**Comment by Veracity0** [comment]
The issue was my local repository was a clone of this repository, not a fork.
I forked and made a pull request from there. So, user error.
Thanks!
